// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsXamlAgain.Runtime")>]
[<assembly: AssemblyProductAttribute("FsXamlAgain")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing FsXamlAgain.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsXamlAgain.Runtime"
    let [<Literal>] AssemblyProduct = "FsXamlAgain"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing FsXamlAgain."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
